# Generated by Django 5.2 on 2025-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('default', models.CharField(blank=True, max_length=100, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('nullable', models.BooleanField(default=True)),
                ('blank', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dynamic_field',
            },
        ),
    ]
