# Generated by Django 5.2 on 2025-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamicfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
