# Generated by Django 5.2 on 2025-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'permissions': [('view_product_public', 'Can view products (Public)'), ('change_product_user', 'Can edit products (User)'), ('delete_product_manager', 'Can delete products (Manager)')],
            },
        ),
    ]
