# Generated by Django 5.2 on 2025-05-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamicfield'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldValueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('dynamic_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dynamicfield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'custom_field_value_product',
            },
        ),
    ]
