# Generated by Django 5.2 on 2025-05-03 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
